--liquibase formatted sql

--changeset courser:001-create-users
CREATE TABLE users (
    id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    email VARCHAR(255) NOT NULL,
    last_login TIMESTAMP(6) WITHOUT TIME ZONE,
    password VARCHAR(255) NOT NULL,
    quizzes_completed INTEGER,
    role VARCHAR(255) NOT NULL,
    total_score INTEGER,
    username VARCHAR(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('STUDENT', 'TEACHER', 'ADMIN'))
);

CREATE SEQUENCE users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE users_id_seq OWNED BY users.id;
ALTER TABLE ONLY users ALTER COLUMN id SET DEFAULT nextval('users_id_seq');

--changeset courser:002-create-quizzes
CREATE TABLE quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME quizzes_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ) NOT NULL,
    title VARCHAR(255),
    owner_user_id BIGINT
);

--changeset courser:003-create-questions
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME questions_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ) NOT NULL,
    content TEXT,
    quiz_id BIGINT NOT NULL,
    question_order INTEGER,
    image_data BYTEA,
    image_filename VARCHAR(255)
);

--changeset courser:004-create-answers
CREATE TABLE answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME answers_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ) NOT NULL,
    content TEXT,
    correct BOOLEAN NOT NULL,
    question_id BIGINT NOT NULL,
    answer_order INTEGER
);

--changeset courser:005-create-quiz-results
CREATE TABLE quiz_results (
    id BIGINT NOT NULL,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    max_score INTEGER NOT NULL,
    quiz_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE SEQUENCE quiz_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE quiz_results_id_seq OWNED BY quiz_results.id;
ALTER TABLE ONLY quiz_results ALTER COLUMN id SET DEFAULT nextval('quiz_results_id_seq');

--changeset courser:006-create-quiz-share-codes
CREATE TABLE quiz_share_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME quiz_share_codes_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ) NOT NULL,
    active BOOLEAN NOT NULL,
    code VARCHAR(10) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE,
    quiz_id BIGINT NOT NULL
);

--changeset courser:007-add-primary-keys
ALTER TABLE ONLY answers ADD CONSTRAINT answers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY questions ADD CONSTRAINT questions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY quiz_results ADD CONSTRAINT quiz_results_pkey PRIMARY KEY (id);
ALTER TABLE ONLY quiz_share_codes ADD CONSTRAINT quiz_share_codes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY quizzes ADD CONSTRAINT quizzes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY users ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--changeset courser:008-add-unique-constraints
ALTER TABLE ONLY users ADD CONSTRAINT uk_6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE ONLY users ADD CONSTRAINT uk_r43af9ap4edm43mmtq01oddj6 UNIQUE (username);
ALTER TABLE ONLY quiz_share_codes ADD CONSTRAINT uk_quiz_share_codes_code UNIQUE (code);

--changeset courser:009-add-foreign-keys
ALTER TABLE ONLY answers
    ADD CONSTRAINT fk3erw1a3t0r78st8ty27x6v3g1 FOREIGN KEY (question_id) REFERENCES questions (id);

ALTER TABLE ONLY questions
    ADD CONSTRAINT fkn3gvco4b0kewxc0bywf1igfms FOREIGN KEY (quiz_id) REFERENCES quizzes (id);

ALTER TABLE ONLY quiz_share_codes
    ADD CONSTRAINT fkma9ee5ntjs2yiohoytg9qvk6c FOREIGN KEY (quiz_id) REFERENCES quizzes (id);

ALTER TABLE ONLY quizzes
    ADD CONSTRAINT fk_quizzes_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);

ALTER TABLE ONLY quiz_share_codes
    ADD CONSTRAINT fk_quiz_share_codes_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users (id);

ALTER TABLE ONLY quiz_results
    ADD CONSTRAINT fk_quiz_results_user_id FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE ONLY quiz_results
    ADD CONSTRAINT fk_quiz_results_quiz_id FOREIGN KEY (quiz_id) REFERENCES quizzes (id);
