--liquibase formatted sql

--changeset courser:015-add-quiz-limits
ALTER TABLE quizzes
    ADD COLUMN max_attempts INTEGER,
    ADD COLUMN quiz_time_seconds INTEGER,
    ADD COLUMN question_time_seconds INTEGER;

ALTER TABLE quizzes
    ADD CONSTRAINT quizzes_max_attempts_check CHECK (max_attempts IS NULL OR max_attempts > 0);

ALTER TABLE quizzes
    ADD CONSTRAINT quizzes_quiz_time_seconds_check CHECK (quiz_time_seconds IS NULL OR quiz_time_seconds > 0);

ALTER TABLE quizzes
    ADD CONSTRAINT quizzes_question_time_seconds_check CHECK (question_time_seconds IS NULL OR question_time_seconds > 0);

--changeset courser:016-create-quiz-attempts
CREATE TABLE quiz_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    started_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    quiz_deadline_at TIMESTAMP(6) WITHOUT TIME ZONE,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT quiz_attempts_status_check CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'EXPIRED', 'CHEATING')),
    CONSTRAINT fk_quiz_attempts_quiz_id FOREIGN KEY (quiz_id) REFERENCES quizzes (id) ON DELETE CASCADE
);

CREATE INDEX idx_quiz_attempts_quiz_user_status ON quiz_attempts (quiz_id, user_id, status);

--changeset courser:017-create-quiz-attempt-questions
CREATE TABLE quiz_attempt_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    started_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    deadline_at TIMESTAMP(6) WITHOUT TIME ZONE,
    submitted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    selected_answer_ids VARCHAR(2000),
    CONSTRAINT fk_quiz_attempt_questions_attempt_id FOREIGN KEY (attempt_id) REFERENCES quiz_attempts (id) ON DELETE CASCADE,
    CONSTRAINT uq_quiz_attempt_questions_attempt_question UNIQUE (attempt_id, question_id)
);
